[build]
  publish = ".next"
  command = "./scripts/netlify-build.sh"

[build.environment]
  NODE_VERSION = "20"
  CANVAS_PREBUILT = "false"
  PYTHON = "/opt/buildhome/.local/share/mise/installs/python/3.13.3/bin/python3"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_FIREBASE_API_KEY
# NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
# NEXT_PUBLIC_FIREBASE_PROJECT_ID
# NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
# NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
# NEXT_PUBLIC_FIREBASE_APP_ID
# FIREBASE_PRIVATE_KEY
# FIREBASE_CLIENT_EMAIL
# FIREBASE_PROJECT_ID
# EMAIL_USER
# EMAIL_APP_PASSWORD
# REDIS_URL 